# =================================================================================
# SECCIÓN DE VARIABLES
# Define todas las variables en un solo lugar para un fácil mantenimiento.
# =================================================================================
substitutions:
  _REGION: 'us-central1'
  _ARTIFACT_REPO: 'airflow-images'
  _IMAGE_NAME: 'airflow-runner'
  _GCS_BUCKET: 'blizzard-airflow-artifacts'

# =================================================================================
# SECCIÓN DE PASOS
# Las instrucciones que ejecutará Cloud Build.
# =================================================================================
steps:
# --- Paso 1: Construir la imagen de Airflow ---
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    # Usa las variables para construir la ruta completa de la imagen.
    - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest'
    - './docker/airflow'
  id: 'Build Docker Image'

# --- Paso 2: Sincronizar la carpeta de DAGs ---
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - 'rsync'
    - '-r'
    - '-d'
    - './dags'
    # Usa la variable para apuntar al bucket correcto.
    - 'gs://${_GCS_BUCKET}/dags'
  id: 'Sync DAGs to GCS'

# =================================================================================
# SECCIÓN DE IMÁGENES
# Le dice a Cloud Build qué imagen debe subir a Artifact Registry.
# =================================================================================
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_IMAGE_NAME}:latest'