apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Debe coincidir con el tamaño en gcs-pv.yaml
  volumeName: airflow-dags-pv
  storageClassName: ""